micronaut:
  http:
    services:
      google-places:
        url: https://maps.googleapis.com
  security:
    authentication: cookie
    token:
      jwt:
        generator:
          refresh-token:
            secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:}"'
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:}"'
  datasources:
    postgres:
      url: // add url
      username: // add user
      password: // add password
      driverClassName: org.h2.Driver
