micronaut:
  http:
    services:
      google-places:
        url: https://maps.googleapis.com
  security:
    authentication: cookie
    token:
      jwt:
        claims-validators:
          audience: true
          issuer: true
          not-before: true

datasources:
  postgres:
    driverClassName: org.postgresql.Driver
    catalog: primary
    schema: baserent
    pool-name: hikari-1

liquibase:
  datasources:
    postgres:
      change-log: 'db/changelog-root.xml'
      liquibase-schema: public

