micronaut:
  http:
    services:
      google-places:
        url: https://maps.googleapis.com
  security:
    authentication: cookie

datasources:
  postgres:
    driverClassName: org.postgresql.Driver
    catalog: primary
    schema: baserent
    pool-name: hikari-1

liquibase:
  enabled: false
