micronaut:
  http:
    services:
      google-places:
        url: https://maps.googleapis.com
  security:
    authentication: cookie
    token:
      jwt:
        generator:
          refresh-token:
            secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:a}"'
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:b}"'
datasources:
  postgres:
    driverClassName: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES

liquibase:
  datasources:
    postgres:
      change-log: 'db/changelog-root.xml'

