micronaut:
  http:
    services:
      google-places:
        url: https://maps.googleapis.com
  security:
    authentication: cookie

datasources:
  postgres:
    driverClassName: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES
